language: java
notifications:
  hipchat:
    rooms:
      secure: cAsIpp3qU6VydHPTq5qQJLFeWFSgE1hkwCUqOZyMk/Tbbv8ApYZglJBRDfkjynbsQbAf+rSYDXxNLVQYsvDOfSiSYIVnKftZHX03EOZPzxTC+sfle1eiNI/FX6CqAj6y7NwOq7Q4BmX30phKgs0n6U2XmeUGFa38m4fro4wI217YtC42kDiHoNxvVcemLTdxv0LNkfktWVBxZua245Tz63kpyRbYhzMGahC4QEmWa8LJqLC2iWt9X2XJrF67xJb8mM446aMITotHfv/N34j+XY6pSlz7Ce5/ocvH5hy/U7zV7n5mGPJa7xgE4RRV9Nzm53iIuB4GjLWIjyhxl49VMlWYLf2g/bvpD8RkJQB2X7ME30QJWmYSKgIEkfD0YccZxbL+LgrmRjZDu7AdnEWm2FsoNQtLMJECm7L+zAZM4GjpdtQ5XIPDuQi0nB4n2TAf3xYynuQUbkimm+kRhti+UUEqvzF62Ul0y6mQ+bM4J8XXXiPpEp2j0xHtPHcamkF2UCx03Z8R2fLEYsNZuU8s/bk1fi0XVs1axzCzKolLgUjaN8gvyvWDzWbaD4B1oW9L0NBxcwEuAKXqNrExxoJcvtknbZHf1NIzI2bTyVfI6kEItMvEAfDaIj1q5epvB3uZZ1EkJWmpcpBiTZesYQ33gjqxrekMart3dia3NZ882QU=
deploy:
  provider: releases
  api_key:
    secure: BlKwegRG4oMhauFPEpz/EamGnizJvH9+QFTVE6qMYNcAdaSfdtFekRPCOq7V0/ScxtjRjJJhqJ/9xDVjlle8aNUeE2ObKtHhzLWKYUJq/T9If9z+V6eweIcLxsOi3g2OrEXKdGE/DUahv/C5klqSvQjYC9B3RoqPpUuy61m5MMFIOGBqrAqN/Quc2j0hzwLSLY+E63UrlOKfNp8v5wrB7IkGHi7rpJd4Dh4yHK5DB9zGlHiaf6R9ovBNYqR7dXd7xN1RtDLpjtJEK0ZnC02w64XIh20/dVgF3ls+yvDh5+j28X0S8wucziy/ZghAOFo0gfGr/8mVf7r/xtsRZAYxe5cizGCig4QIuoNnDeYmsZASO8hnH2apjy9/fMniyp9D66V5ySatqfjQEuqFDVQUwxTnsu8ysgUxDMRCkjaKW3OIwXtNzJR5FYf8ZCTBbnfMtqm2gItsvKW2VvgF/Yr/wje9oL9wyjeJDq5XVM9BgKdbrtOBmAKL3O3wke55fwROc7sjEThxi9H8hjJb+t7xoxjW+7R6jnGvzGV0XV4hQoircNGICyPTa8JPZKJTYi8ZZB/psH7NzkiJAuJ29gSbsAzvnOmFZO8y3cG5vHM4bPdWY4T17hGIZ6GJPS4twIcxJpFFVCq6bQj9wNq/LE/vF4UeObKvr/r3Kc/UndTGzZM=
  file: build/libs/xlr-splunk-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-splunk-plugin
